#include "slam/camera_config.hpp"

#include <fstream>
#include <iomanip>

#include <opencv2/core/persistence.hpp>

#include "common/logging.hpp"

namespace slam {

bool readCameraConfig(const std::string& path, CameraConfigInfo& info) {
    cv::FileStorage fs(path, cv::FileStorage::READ);
    if (!fs.isOpened()) {
        common::logError("CameraConfig", "cannot read camera config: " + path);
        return false;
    }

    const auto readNumber = [&fs](const char* key, double fallback) {
        const cv::FileNode node = fs[key];
        return node.empty() ? fallback : static_cast<double>(node);
    };

    info.width = static_cast<int>(readNumber("Camera.width", 0));
    info.height = static_cast<int>(readNumber("Camera.height", 0));
    info.fps = static_cast<int>(readNumber("Camera.fps", 30));
    info.fx = readNumber("Camera1.fx", 0.0);
    info.fy = readNumber("Camera1.fy", 0.0);
    info.cx = readNumber("Camera1.cx", 0.0);
    info.cy = readNumber("Camera1.cy", 0.0);
    info.k1 = readNumber("Camera1.k1", 0.0);
    info.k2 = readNumber("Camera1.k2", 0.0);
    info.p1 = readNumber("Camera1.p1", 0.0);
    info.p2 = readNumber("Camera1.p2", 0.0);
    info.k3 = readNumber("Camera1.k3", 0.0);

    if (info.width <= 0 || info.height <= 0 || info.fx <= 0.0) {
        common::logError("CameraConfig",
                          "camera config is missing Camera.width/height or Camera1.fx: " + path);
        return false;
    }

    // ORB-SLAM3 requires every camera parameter to be a REAL node and calls
    // exit() if one is an integer - so "Camera1.fx: 900" aborts the process
    // with a one-line message and no hint about which file is at fault,
    // while "900.0" works. Catch it here, where we can say something useful.
    for (const char* key : {"Camera1.fx", "Camera1.fy", "Camera1.cx", "Camera1.cy",
                             "Camera1.k1", "Camera1.k2", "Camera1.p1", "Camera1.p2",
                             "Camera1.k3"}) {
        const cv::FileNode node = fs[key];
        if (!node.empty() && !node.isReal()) {
            common::logError("CameraConfig",
                              std::string(key) + " in " + path +
                                  " is not a real number. Write it with a decimal point (900.0, "
                                  "not 900) - ORB-SLAM3 rejects integer camera parameters.");
            return false;
        }
    }
    return true;
}

bool writeCameraConfig(const std::string& path, const CameraConfigInfo& info) {
    std::ofstream out(path);
    if (!out) {
        common::logError("CameraConfig", "cannot write camera config: " + path);
        return false;
    }

    out << std::fixed << std::setprecision(6);
    out << "%YAML:1.0\n\n";
    out << "# Generated by apps/tools/calibrate_camera. Intrinsics are in pixels and\n"
           "# are only valid at the resolution below - feed SLAM images of exactly\n"
           "# this size (the video sources' target_width/target_height do that).\n\n";
    out << "File.version: \"1.0\"\n\n";
    out << "Camera.type: \"PinHole\"\n\n";
    out << "Camera1.fx: " << info.fx << "\n";
    out << "Camera1.fy: " << info.fy << "\n";
    out << "Camera1.cx: " << info.cx << "\n";
    out << "Camera1.cy: " << info.cy << "\n\n";
    out << "Camera1.k1: " << info.k1 << "\n";
    out << "Camera1.k2: " << info.k2 << "\n";
    out << "Camera1.p1: " << info.p1 << "\n";
    out << "Camera1.p2: " << info.p2 << "\n";
    out << "Camera1.k3: " << info.k3 << "\n\n";
    out << "Camera.width: " << info.width << "\n";
    out << "Camera.height: " << info.height << "\n";
    out << "Camera.fps: " << info.fps << "\n";
    out << "# 0 = BGR, which is what video/ produces. Do not change.\n";
    out << "Camera.RGB: 0\n\n";
    out << "ORBextractor.nFeatures: 1500\n";
    out << "ORBextractor.scaleFactor: 1.2\n";
    out << "ORBextractor.nLevels: 8\n";
    out << "ORBextractor.iniThFAST: 20\n";
    out << "ORBextractor.minThFAST: 7\n\n";
    out << "Viewer.KeyFrameSize: 0.05\n";
    out << "Viewer.KeyFrameLineWidth: 1.0\n";
    out << "Viewer.GraphLineWidth: 0.9\n";
    out << "Viewer.PointSize: 2.0\n";
    out << "Viewer.CameraSize: 0.08\n";
    out << "Viewer.CameraLineWidth: 3.0\n";
    out << "Viewer.ViewpointX: 0.0\n";
    out << "Viewer.ViewpointY: -0.7\n";
    out << "Viewer.ViewpointZ: -3.5\n";
    out << "Viewer.ViewpointF: 500.0\n";

    common::logInfo("CameraConfig", "wrote " + path);
    return out.good();
}

} // namespace slam
